Optimized while loop, implamented QbCore Functions
qbcore-framework/qb-scoreboard pull request #22
Opened 2022-03-27 10:30 UTC by Rav3n95

2022-04-07 11:29 UTC, BerkieBb commented
The purpose of having those local functions is optimization, using local function is faster than using that of an object

2022-04-07 11:31 UTC, BerkieBb requested changes

2022-04-07 11:31 UTC, BerkieBb commented on client.lua
> +    local loop = 1000
This can be declared inside the loop instead

2022-04-07 11:31 UTC, BerkieBb commented on client.lua
> +        else
This else is unnecessary if you just declare the loop variable inside the loop

2022-04-07 11:31 UTC, BerkieBb commented on client.lua
> +            loop = 0
Place this inside the if statement instead of outside it so it doesn't wait 0 for nothing

2022-04-07 15:34 UTC, Rav3n95 commented
Let me fix these tomorrow.

2022-04-08 08:57 UTC, Rav3n95 commented
> The purpose of having those local functions is optimization, using local function is faster than using that of an object

While loops are fixed, should i just revert those local function then?

2022-04-08 13:45 UTC, BerkieBb commented
Yes please

2022-04-08 13:47 UTC, Rav3n95 commented
> Yes please

Sure, give me a minute. I just tougth its impelented to core for reasaon.

2022-04-08 13:51 UTC, BerkieBb commented
> > Yes please
> 
> Sure, give me a minute. I just tougth its impelented to core for reasaon.

Those were there before we knew local functions were better to use, so now we keep them for backwards compatibility

2022-04-08 13:52 UTC, Rav3n95 commented
> > > Yes please
> > 
> > 
> > Sure, give me a minute. I just tougth its impelented to core for reasaon.
> 
> Those were there before we knew local functions were better to use, so now we keep them for backwards compatibility

Ohh i understand now, you always help a lot. Thank you.

2022-04-08 14:04 UTC, BerkieBb approved these changes

2022-04-11 05:37 UTC, merged